title: Cd BLOG
author: cdurheart
email: cdurheart@outlook.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  西地游豪

# social links
github_username:  cdurheart # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
