title: BLOG
author: cdurheart
email: cdurheart@outlook.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  随便写写

# social links
twitter_username: cdurheart # DO NOT include the @ character, or else the build will fail!
github_username:  cdurheart # DO NOT include the @ character, or else the build will fail!
wechat_username:  cd urheart

show_excerpts: true # set to false to remove excerpts on the homepage
